### ISSUE TITLE
Embed NetLimiter Api

### ISSUE THREAD

**Issue by KFKMan** [Baseult/NetLimiterCrack#1]
How can i use NetLimiter Api without NetLimiter installed?

**Comment by yui1987** [comment]
Thank you！！

**Comment by doge1311** [comment]
kinda sketchy man why is it labeled as malware

**Comment by SupertoineFR** [comment]
That's because it's a keygen, and most anti-virus solutions consider keygen as malware.
Don't worry about running this keygen on your pc, it's 100% safe.

**Comment by Baseult** [comment]
> kinda sketchy man why is it labeled as malware

Because it modifys the memory of the net limiter auth dll which is necessary for it to work.  It is open source so if you are concerned about it just look through it and compile it yourself.

**Comment by shoe7ess** [comment]
Why is the source code getting blocked automatically as malicious by chrome? I'd assume the source would at the most might trigger win antivirus at most, but I can't get any package (without lowering security) now (2025)
